# Criar um endereco GCP e guarda como variavel
- name: Create GCP address
  google.cloud.gcp_compute_address:
    name: ghostaddress
    region: us-central1
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: address

# Atualiza as variaveis necessarias para o ghost
- name: Update variables
  set_fact:
    ghost_ip: "{{ address }}"
    ghost_port: 80



